services:
  Zuske/AuthClient/Resolve/AuthServiceResolver:
    arguments: ['%env(OAUTH_RESOURCE_OWNER)%', '%env(resolve:OAUTH_URL)%','%env(OAUTH_RESPONSE_TYPE)%', '%env(OAUTH_GRAN_TYPE)%', '%env(OAUTH_CLIENT_ID)%', '%env(OAUTH_CLIENT_SECRET)%', '%env(resolve:OAUTH_REDIRECT_URI)%', '%env(OAUTH_SCOPE)%']
